### ISSUE TITLE
Integrate with the custom URL plugin

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-phone#122]
Define custom URLs (e.g. emission://)

Integrate with them using the custom URL plugin
https://github.com/EddyVerbruggen/Custom-URL-scheme

when the app is opened, extract the group ID and show it in a popup

**Comment by shankari** [comment]
Please define the URL first because #121 depends on it

**Comment by shankari** [comment]
Another option is to use the branch service.
I have no experience with it - you have to play with it to find out.
https://branch.io

**Comment by krisma** [comment]
Briefing on branch.io

I walked through that, in a couple of minutes, and noticed that it's just a SDK for what we are trying to do, and try to charge you for more complicated function. 
The function we can make use of in SDK:
1. Branch.initSession(); // start branch session
2. function DeepLinkHandler(data) { // the handler when app starts, do something here
3. var params = branch.data(); // retrieve metadata we include in link, after user click the link, after step 1, but before user minimize the app (after which the session is wiped out).

What we might need: 
1. habitica ID // since we can't use email, and we have no emission uuid, we can only use habitica id, and search for them.

I think that's it

**Comment by shankari** [comment]
Is their plugin open source? Do we know if they collect any other data? If so, we should do a custom version because otherwise we need to file an IRB amendment.

Also, given this
> I walked through that, in a couple of minutes, and noticed that it's just a SDK for what we are trying to do, and try to charge you for more complicated function.

what do you recommend? use them or not?

**Comment by krisma** [comment]
I think we can try it in a new branch. If it doesn't work, we build our own. I can't tell if it collects more information other than parameters we choose to include.

**Comment by shankari** [comment]
>  I can't tell if it collects more information other than parameters we choose to include.

Is the source code for their SDK available?

**Comment by krisma** [comment]
The source code is available. Both the native code and JS wrapper.

**Comment by shankari** [comment]
Can you add a link to the code here so that I can take a look? Also, is there an ETA on when we can make a decision? I want to add the correct plugins in the next native release.

**Comment by krisma** [comment]
https://github.com/BranchMetrics

I can't decide because I missed out some context you discussed when I wasn't here. In particular, what makes you think branch.io could do that customurl couldn't? They seem to be the same except branch supports more functions that we don't need for now.

**Comment by shankari** [comment]
We actually didn't :)
I just saw branch.io on the page for the custom URL plugin, and thought that we could use it if it was easier. If it is not easier, go for the custom URL plugin. I just wanted you to evaluate them and make a decision.

> since we can't use email, and we have no emission uuid, we can only use habitica id, and search for them.

we should get the emission uuid (we will need it for the game survey anyway)

**Comment by krisma** [comment]
I think we need a hackathon some time to get the invitation work. Otherwise it could take too long. What do you think?

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/130
