### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-phone#39]

**Comment by krisma** [comment]
I implemented pull to refresh. However, the refresher is known to be buggy in this version of ionic framework. It's fixed in version 2.0. [http://stackoverflow.com/questions/35836687/ionic-2-ion-refresher-always-fired-when-pulling-up-after-the-on-refresh-function](url)
The bug I encountered was exactly the same as asked above. Do you think we get to update to 2.0? Otherwise, it would be tricky to handle.

**Comment by shankari** [comment]
The bug that you see is reported on ionic 2 as well.
ionic CLI v2.0.0-beta.17

I have pull to refresh implemented in one of the log screens (recent -> sensed data) and it works fine.
https://github.com/e-mission/e-mission-phone/blob/94fcb64701912ea5855261f2edc82f6b61ddabd7/www/templates/recent/sensedData.html#L3

**Comment by krisma** [comment]
Our codes are essentially the same. Do you have the bug on simulator? cuz your refresher works fine on phone. I can't test the sensed data on simulator for unknown reason. Nothing is fetched.

**Comment by shankari** [comment]
well, probably because there is no data to fetch :)

If you want to get some data to fetch and test in the simulator, choose "transitions" as the type of sensed data, and then make sure that there are some transitions by forcing the state from the control screen or starting and stopping tracking.

**Comment by krisma** [comment]
I have no idea how you avoid the bug. My html part is exactly the same to yours and my js part was the original function. I resolved it by disabling the refresh function when the scroll is not at the top of the window. The trick works.

**Comment by shankari** [comment]
Ok, so I'm gonna get a pull request?

Shankari

**Comment by shankari** [comment]
Fixed by a0554bce08e5c62cce41abbbedcc61f699e27328 in #44
